/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: titopetri (https://sketchfab.com/titopetri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jogador-player-cartoon-boy-toscoman-3d-31f6125b601d4c78a8da0a8fbe1d8672
Title: Jogador | Player - Cartoon Boy - ToscoMan 3D
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


import scene from '../assets/3d/boy.glb'

const Boy = ({currentAnimation, ...props}) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)

  //set animation play state
  useEffect(() => {
   
    Object.values(actions).forEach((action) => action.stop())
    if(actions[currentAnimation]) {
        actions[currentAnimation].play();
    }
    
  },[actions, currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.039}>
          <group name="57c997ae9f2a4deab60978b0d29acb12fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="TOSCOMAN_CTRL_PARENT"
                  position={[0, 0, 2.137]}
                  rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_8"
                      geometry={nodes.Object_8.geometry}
                      material={materials.Material_27}
                      skeleton={nodes.Object_8.skeleton}
                    />
                    <group
                      name="Object_7"
                      position={[0, -0.165, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                    />
                    <group
                      name="TOSCOMAN_CTRL_PE_ESQUERDO"
                      position={[3.498, 1.632, 0]}
                      rotation={[0, 0, 0.509]}>
                      <group
                        name="TOSCOMAN_CTRL_IK__ESQUERDO"
                        position={[0.136, 2.085, 2.888]}
                        rotation={[0, 0, -0.227]}
                      />
                    </group>
                    <group
                      name="TOSCOMAN_CTRL_PE_DIREITO"
                      position={[-4.507, 0.806, 0]}
                      rotation={[0, 0, -0.374]}>
                      <group
                        name="TOSCOMAN_CTRL_IK__DIREITO"
                        position={[-0.135, 2.085, 2.888]}
                        rotation={[0, 0, 0.227]}
                      />
                    </group>
                    <group name="TOSCOMAN_MESH_CORPO" position={[0, 2.137, -0.165]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Boy
